Repository ECP-copa/CabanaMD, pull requests merged in 2020-08, with the labels that each got.

#69 Fix typo "CabanaMD_ENABLE_ARBORX => Cabana_ENABLE_ARBORX"
  src/mdfactory.h
  unit_test/tstNeighbor.hpp
Labels: bug

#71 Add missing and reorder includes
  src/binning_cabana.h
  src/binning_cabana_impl.h
  src/cabanamd.h
  src/cabanamd_impl.h
  src/comm_mpi.h
  src/comm_mpi_impl.h
  src/force.h
  src/force_types/force_lj_cabana_neigh.h
  src/force_types/force_nnp_cabana_neigh.h
  src/force_types/force_nnp_cabana_neigh_impl.h
  src/force_types/modules_system_nnp.h
  src/force_types/types_nnp.h
  src/inputCL.cpp
  src/inputCL.h
  src/inputFile.h
  src/inputFile_impl.h
  src/integrator_nve.h
  src/mdfactory.h
  src/modules_force.h
  src/modules_neighbor.h
  src/modules_system.h
  src/neighbor.h
  src/neighbor_types/neighbor_tree.h
  src/neighbor_types/neighbor_verlet.h
  src/output.cpp
  src/output.h
  src/property_kine.h
  src/property_pote.h
  src/property_pote_impl.h
  src/property_temperature.h
  src/property_temperature_impl.h
  src/read_data.h
  src/system.h
  src/system_types/system_1aosoa.h
  src/system_types/system_2aosoa.h
  src/system_types/system_6aosoa.h
  src/system_types/system_nnp.h
  src/system_types/system_nnp_1aosoa.h
  src/system_types/system_nnp_3aosoa.h
Labels: bug

#72 Add ArborX neighbor lists with 2D layout
  src/inputCL.cpp
  src/mdfactory.h
  src/neighbor_types/neighbor_tree.h
  src/types.h
Labels: enhancement

#78 Enable user preallocation for Verlet neighbor lists
  input/in.lj
  src/cabanamd_impl.h
  src/inputFile.h
  src/inputFile_impl.h
  src/neighbor.h
  src/neighbor_types/neighbor_tree.h
  src/neighbor_types/neighbor_verlet.h
  unit_test/tstNeighbor.hpp
Labels: performance

#79 Fix Cuda unit tests
  unit_test/tstIntegrator.hpp
  unit_test/tstNeighbor.hpp
Labels: bug
